spring:
  application:
    name: client-demo

server:
  port: 30010

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://192.168.233.129:2181