server:
  port: 10020
spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    sentinel:
      master: mymaster
      nodes: 172.18.5.137:26380,172.18.5.137:26381,172.18.5.137:26382
logging:
  level:
    root: debug