server:
  port: 50010
spring:
  rabbitmq:
    host: 192.168.30.130
    port: 5672
    virtual-host: /dev
    username: admin
    password: passwd
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true