server:
  port: 50010
spring:
  redis:
    client-type: lettuce
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    sentinel:
      master: mymaster
      nodes: 192.168.30.130:26381,192.168.30.130:26382,192.168.30.130:26383