server:
  port: 20010
spring:
  application:
    name: springcloudgateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: integrated-gateway
    gateway:
      routes:
        - id: servicea
          uri: lb://servicea
          predicates:
            - Path=/servicea/**
        - id: serviceb
          uri: lb://serviceb
          predicates:
            - Path=/serviceb/**