server:
  port: 20010
spring:
  application:
    name: springcloudgateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: springcloud-demo
    gateway:
      routes:
        - id: servicea
          uri: lb://service-a
          predicates:
            - Path=/servicea/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
        - id: serviceb
          uri: lb://service-b
          predicates:
            - Path=/serviceb/**
          filters:
            - StripPrefix=1