# kubectl apply -f <file_name>.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  key1: value1
  key2: value2
  config.json: |
    {
      "setting1": "value1",
      "setting2": "value2"
    }